### ISSUE TITLE
Fix: label is not reset when clearing selected options from button dropdown

### ISSUE THREAD

**Issue by Deeved** [Brisanet/ion#435]
## Description

Label is not reset when clearing selected options from button dropdown

## Screenshots

![fix_ button with dropdown](https://user-images.githubusercontent.com/64809323/216151538-7809df1f-8d8f-483f-8d1f-09548ffc58f0.gif)

**Comment by iurynogueira** [comment]
@larissacard

**Comment by mizek1** [comment]
This was solved by #445.
