### ISSUE TITLE
Insert all available icons in the storybook

### ISSUE THREAD

**Issue by AlyssonMascarenhas** [Brisanet/ion#463]
## Description

Through the storybook, a user does not have access to all the icons implemented in the system.

## Expected Behavior

When accessing the storybook in icons, you will see the list of all available icons.

## Current Behavior

Open the code and see the implemented ones

## Screenshots

![image](https://user-images.githubusercontent.com/54484070/219745749-ca65c5b0-ad47-4b8d-ae05-e64cdcb6308d.png)
![image](https://user-images.githubusercontent.com/54484070/219746299-e7b13376-c24e-4690-ac37-f31fdabbd83d.png)

## Additional Information

Model in AntDesign:
![image](https://user-images.githubusercontent.com/54484070/219746792-0eea08ce-a8ab-48d7-ab61-b90de5341ba1.png)

**Comment by mizek1** [comment]
I think we should also add all icons that are already made by designers, it would avoid having to upload a version just because someone needed a specific icon that is not yet available, for example. What do you think @iurynogueira?

**Comment by iurynogueira** [comment]
Great! I had created a issue to improve this before https://github.com/Brisanet/ion/issues/285

**Comment by Lucassec1** [comment]
can assign me? 🙃

**Comment by iurynogueira** [comment]
@Lucassec1 assigned

**Comment by Lucassec1** [comment]
![image](https://user-images.githubusercontent.com/106749169/226373338-a0cdf51f-b1f5-4f17-a85a-6e38afa9eee4.png)
I'm mapping the icons with a mock, however the two icons below are not being rendered.

![image](https://user-images.githubusercontent.com/106749169/226373882-e890cb57-f8a5-4c0a-9782-0070c6929024.png)
Entering the icon, it has an svg and a path inside, however the other icons only have the path.

![image](https://user-images.githubusercontent.com/106749169/226374820-dae8419e-a873-416b-a582-68fa94836f99.png)
Removing the svg from both and leaving just the path it renders, plus the icon is not centered even with the svg or after I remove it.

![image](https://user-images.githubusercontent.com/106749169/226375735-8cb542cd-1356-4d9e-8265-b69e99252d00.png)
Trying to render it in Storybook in Design Tokens/Icons/Icon Default, it doesn't render either.

What do you think could be the best thing to do @iurynogueira?
