### ISSUE TITLE
Fix z-index tooltip

### ISSUE THREAD

**Issue by AlyssonMascarenhas** [Brisanet/ion#489]
## Description

When any element of a modal (either an element or an HTML element) has the ionTooltip, it is rendered behind the modal, making it impossible to visualize it.

## Expected Behavior

When using the tooltip in a modal, or something like that, it overrides the modal view.

## Current Behavior

Currently the tooltip is rendered behind the modal, not being able to see it.

## Steps to Reproduce

Create a component with any HTML element using ionTooltip, and call it in ionModalService, when trying to access the tooltip it will not be possible to view it.

## Screenshots

ionTooltip is rendered but not shown.
![image](https://user-images.githubusercontent.com/54484070/222139453-d0744828-2433-4ce6-a29c-53cae06c2567.png)

When adding the z-index it is shown.
![image](https://user-images.githubusercontent.com/54484070/222139614-0fb471f6-b926-4798-8850-10c668549092.png)

## Additional Information

Adding a z-index to ionTooltip might do the trick.

**Comment by dayannebugarim** [comment]
can assign me?

**Comment by AlyssonMascarenhas** [comment]
Yes, you can.

**Comment by mizek1** [comment]
Solved on #504.
