### ISSUE TITLE
Popconfirm needs to appear in visible area of the screen

### ISSUE THREAD

**Issue by wermesonsl** [Brisanet/ion#535]
## Description

When using popconfirm on a table, it opens in a non-visible area of the page, creating a temporary horizontal scroll.

## Expected Behavior

Since it's opening from the far right of the screen, ideally that it would open to the left side.

## Current Behavior

When clicking, it's opening to the right, even though there's no space there. So it creates a space, and scroll, which only exists as long as it's open on the screen.

## Screenshots

![Captura de tela de 2023-03-28 16-14-10](https://user-images.githubusercontent.com/63553747/228554377-3a2acf3a-6b80-40b0-901b-f30a725c44bb.png)

![Captura de tela de 2023-03-28 16-14-04](https://user-images.githubusercontent.com/63553747/228554398-0071c9de-275c-4152-925a-a2514c250f97.png)

**Comment by dayannebugarim** [comment]
I would like to try it, can you assign me? :)
