### ISSUE TITLE
Adjustments in the table component

### ISSUE THREAD

**Issue by wermesonsl** [Brisanet/ion#536]
## Description

When using the table on a screen, I ended up noticing some things that are interesting to adjust.

- Apply background color to the table, so that way it will not transparent, because, depending on the background color of the page, it may look strange or even not contribute to contrast colors;
- When there is no data for a cell, add a dash (-). (This function may be optional for the developer to call).

These observations speak out about pagination as used in the table:

- When using pagination, the table is issuing two event calls to the page, causing twice call for listing route;
- Pagination is not accepting 0 as the value of total items. Not displaying any pagination button.

## Expected Behavior

- That the table rows have defined colors, including base colors such as neutral-1 (from the Ion color library). The same goes for the "No data" message;
- Autocomplete option with dash (-) when there is no data in any cell;
- Issue only one event call per action on the table;
- Show pagination buttons disabled when total is 0.

## Screenshots

![Captura de tela de 2023-03-28 08-10-16](https://user-images.githubusercontent.com/63553747/228558124-36da9f35-12b0-49f4-b7d7-af513674b908.png)

![Captura de tela de 2023-03-28 08-10-46](https://user-images.githubusercontent.com/63553747/228558167-5f7cfee4-882c-4c0c-8087-b89b999ae052.png)

![Captura de tela de 2023-03-29 10-41-22](https://user-images.githubusercontent.com/63553747/228558252-5576a24e-3310-4b6d-9070-457abc77e832.png)

**Comment by iurynogueira** [comment]
We need a discussion with design team about this.
