### ISSUE TITLE
Adjustment to the Button component.

### ISSUE THREAD

**Issue by andersonnagelo** [Brisanet/ion#561]
There is no disabled variation with loading.
![image](https://user-images.githubusercontent.com/31452157/230075802-93c7c771-125a-4692-a62c-6f911558dcd3.png)

**Comment by Lucassec1** [comment]
can I do this? :D

**Comment by Lucassec1** [comment]
it's just to remove the disabled on loading, right? @andersonnagelo

**Comment by andersonnagelo** [comment]
It's the opposite, you should remove the loading from the button in the disabled state. @Lucassec1
