### ISSUE TITLE
Adjustment to the Breadcrumb component.

### ISSUE THREAD

**Issue by andersonnagelo** [Brisanet/ion#562]
Change the color of the arrows (neutral 5) and the behavior (when clicking on the previous page, the following pages disappear).
![image](https://user-images.githubusercontent.com/31452157/230078815-7886f782-1c25-42a9-815d-64add3ecdbdb.png)

**Comment by mizek1** [comment]
The behaviour should be on another issue because it's a lot more complex to be developed, we'll probably need to add a service to breadcrumbs.
This issue will only fix the arrow colors.
