### ISSUE TITLE
Adjustment to the Chip component.

### ISSUE THREAD

**Issue by andersonnagelo** [Brisanet/ion#564]
Add the counter when selecting the item, the option to clear the search is not implemented.
![image](https://user-images.githubusercontent.com/31452157/230079703-d515937a-bfe1-4ae6-9efc-79d3d8a042d6.png)

**Comment by iurynogueira** [comment]
Storybook bug

**Comment by iurynogueira** [comment]
fixed counter on https://github.com/Brisanet/ion/commit/465cc9bea931c6f98673ac5ad970c7e357a425c9
