### ISSUE TITLE
Adjustment to the Card component.

### ISSUE THREAD

**Issue by andersonnagelo** [Brisanet/ion#570]
Adjust dropdown (content position)
![image](https://user-images.githubusercontent.com/31452157/230099433-aacfeba5-00ad-4435-9e2f-926d9f0dc26c.png)

**Comment by iurynogueira** [comment]
Fixed

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/6165180/232601622-6482f749-1d25-42aa-95dd-0431fbfbf9a9.png">
