### ISSUE TITLE
Adjustment to the Tag component

### ISSUE THREAD

**Issue by andersonnagelo** [Brisanet/ion#571]
Adjust content spacing, font line height, and box size.
![image](https://user-images.githubusercontent.com/31452157/230099785-25ec74f4-1b2e-49ae-8244-1dc0a7c25132.png)

**Comment by Lucassec1** [comment]
What change do you want in the box size @andersonnagelo?

**Comment by andersonnagelo** [comment]
@Lucassec1 There is a variation in the total size of the tag box, which should be 24px high for everyone. And in content height, it should be 16px. and the tag itself should be 20px tall, but it should be placed in a 24px box, similar to the icon.
![image](https://user-images.githubusercontent.com/31452157/231490120-f85bb3cb-bb35-4b5b-b390-7c3266906cb0.png)
