### ISSUE TITLE
Adjustment to the Badge component

### ISSUE THREAD

**Issue by andersonnagelo** [Brisanet/ion#573]
The icon should occupy the size of 12x12, not requiring a box.
![image](https://user-images.githubusercontent.com/31452157/230100522-6e813a56-63bf-4169-8c5e-0096faa03ea9.png)

**Comment by iurynogueira** [comment]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/6165180/232598708-a2e6a113-3db8-43af-8840-ec6cd0e34724.png">
