### ISSUE TITLE
fix: ion-button click event on card

### ISSUE THREAD

**Issue by PedroMiguel7** [Brisanet/ion#779]
The card is currently using ion-button with the 'click' event, instead of 'ionOnClick'. This has led to some issues, such as triggering the event when the button is disabled. To resolve this, I propose updating the implementation to use 'ionOnClick' instead. This will ensure consistent behavior and prevent any potential errors when applying functionalities to ion-button in the future. As in:  #777.

**Comment by jAllanOli** [comment]
The buttons in this component doesnt have the disable property neither has it on its type, is this something that should be reviewed?

**Comment by PedroMiguel7** [comment]
@jAllanOli, Although the buttons in this component may not currently have the "disabled" property, using "ionOnClick" ensures consistency and avoids potential behavior errors. This makes any functionality applied to the ion-button effective in all cases that use it. This proactive approach prepares us for possible future updates or improvements related to the ion-button

**Comment by jAllanOli** [comment]
Maybe I miss expressed. I think its super valid to update the click listeners, I got that point. I was just raising the point that the button on the component is missing that property, and thats the thing that should be reviewed, that specific button and its type.

**Comment by PedroMiguel7** [comment]
Ah, I misunderstood then, sorry. I think the question is very valid. 😂

**Comment by jAllanOli** [comment]
No problem, i think the main problem with this button is that it has its own type but it should at least extend the ion button type.
