### ISSUE TITLE
fix: ion-button click event on pagination

### ISSUE THREAD

**Issue by PedroMiguel7** [Brisanet/ion#784]
The pagination is currently using ion-button with the 'click' event, instead of 'ionOnClick'. This has led to some issues, such as triggering the event when the button is disabled. To resolve this, I propose updating the implementation to use 'ionOnClick' instead. This will ensure consistent behavior and prevent any potential errors when applying functionalities to ion-button in the future.

As in: https://github.com/Brisanet/ion/issues/777.

**Comment by jAllanOli** [comment]
Is there a specific reason for the pagination "number" buttons to be regular buttons instead of ion-buttons? (I implemented the advanced but followed the pattern of the regular one)
