### ISSUE TITLE
Change information icon from indicator 

### ISSUE THREAD

**Issue by iurynogueira** [Brisanet/ion#963]
Replace icon to:

![image](https://github.com/Brisanet/ion/assets/6165180/a666e558-7084-452c-a1df-86938a5b3998)

**Comment by sfazli96** [comment]
Hi! Can I be assigned to this issue? I can give it a try. Please assign me to it

**Comment by sfazli96** [comment]
Also, where in the files can this change be done?

**Comment by iurynogueira** [comment]
> Also, where in the files can this change be done?

Hi! This icon file is already in IonIcon, you only need change the IconType name, check icon list here https://main--62eab350a45bdb0a5818520e.chromatic.com/

**Comment by sfazli96** [comment]
Ok so I gave it a try and made a pull request, I hope that is ok.

**Comment by iurynogueira** [comment]
> Ok so I gave it a try and made a pull request, I hope that is ok.

Your change need be in indicator component.

![image](https://github.com/Brisanet/ion/assets/6165180/5f65357d-2e7c-4223-a1cf-d4cd2e180a4f)

change this type to `information`.

**Comment by sfazli96** [comment]
Ok I see, I can do that as soon as possible. Thanks!
